// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

declare global {
	namespace NodeJS {
	  interface ProcessEnv {
		[key: string]: string | undefined;
		DB: D1Database;
	  }
	}
  }
  export { };